### ISSUE TITLE
Rewrite the PeopleFinder Quickstart

### ISSUE THREAD

**Issue by glennblock** [aserto-dev/aserto-docs#136]
```[tasklist]
### Tasks
- [x] Update the overview
- [x] Add deploying to Netlify
- [x] Update the Explore page
- [x] Add exploring the RBAC policy in the policy viewer
- [x] Add changing from RBAC to REBAC to add a new feature
```
